version: "3"
services:
  front:
    volumes:
    - ./front/app:/workspace/front:cached
  post:
    volumes:
    - ./post/app:/workspace/post:cached
  entry-store:
    volumes:
    - ./entry-store/app:/workspace/entry-store:cached
  database:
    ports: 
      - "27017:27017"
  netshoot:
    image: nicolaka/netshoot
    restart: always
    command: sleep infinity
    networks:
      - default
      - autharitus

